console.log("hello there".toUpperCase())
console.log("im hungry".toUpperCase())
 console.log(" |    |")
 console.log(" |    |")
 console.log(" |    |")
 console.log("--------")
 console.log(" |    |")
 console.log(" |    |")
 console.log(" |    |")
 console.log("--------")
 console.log(" |    |")
 console.log(" |    |")
 console.log(" |    |")